### PR TITLE
Updates New Event Sorting Method

### PR DESCRIPTION
**Pull request by JeffNeff**
Includes an Icon in the top right that swaps incoming events direction. This closes issue [#16](https://github.com/n3wscott/sockeye/issues/16) in the `sockeye` repo

### CODE REVIEW

**Comment by JeffNeff** [comment]
Screen Shot 2021-09-08 at 2 49 45 PM

Notice the new icon in the top right marked in red. When this icon is clicked the incoming event direction is swapped. 

Screen recording displaying functionality -> https://streamable.com/866rx4

**Comment by n3wscott** [comment]
with a similar change I was not able to get the lock button to work in a way that was not distracting when the new events stream in. Let me try this out! thanks!!

**Review by n3wscott — APPROVED** [review]
LGTM

**Comment by n3wscott** [comment]
ah shoot, some conflicts from the other PR.

**Pull request merged**
